# Generated by Django 2.1.4 on 2018-12-16 00:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('description_verbose', models.CharField(max_length=256)),
                ('qual_name', models.CharField(max_length=64)),
                ('state', django.contrib.postgres.fields.jsonb.JSONField()),
                ('doc', models.TextField()),
            ],
        ),
    ]
