# Generated by Django 2.1.4 on 2018-12-16 01:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', django.contrib.postgres.fields.jsonb.JSONField()),
                ('node_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_node_from', to='calc.Node')),
                ('node_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_node_to', to='calc.Node')),
            ],
        ),
    ]
