# Generated by Django 2.1.4 on 2018-12-18 18:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_edge'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.IntegerField()),
                ('result', django.contrib.postgres.fields.jsonb.JSONField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_node', to='calc.Node')),
            ],
        ),
    ]
