# Generated by Django 2.1.4 on 2018-12-18 18:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_noderun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noderun',
            name='result',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
