# Generated by Django 2.1.4 on 2019-01-25 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_auto_20190125_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noderun',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_node_run', to='calc.NodeResult'),
        ),
    ]
