# Generated by Django 2.1.4 on 2019-02-21 04:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_auto_20190125_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='type',
            field=models.CharField(default='dataflow', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='postprocessing',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='preprocessing',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='node',
            name='qual_name',
            field=models.CharField(max_length=256),
        ),
    ]
