version: '3'
services:
  django:
    build: ./backend
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./data:/data
    depends_on:
      - "postgres"
    command: sh -c './wait-for postgres:5432 -- ./entrypoint.sh'
    networks:
      - nginx_network
      - database_network
      - worker_network

  celery:
    build: ./backend
    volumes: 
      - static_volume:/app/static
      - media_volume:/app/media
      - ./data:/data
    depends_on:
      - "django"
      - "redis"
    command: sh -c 'celery -A jabberwocky worker -l info'
    networks:
      - database_network
      - worker_network

  postgres:
    image: "postgres:alpine"
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - database_network

  nginx:
    image: "nginx:alpine"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./frontend/dist/frontend:/opt/frontend/dist
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - "django"
    networks:
      - nginx_network

  redis:
    image: "redis:alpine"
    networks:
      - worker_network

networks:
  nginx_network:
    driver: bridge
  database_network:
    driver: bridge
  worker_network:
    driver: bridge
  
volumes:
  static_volume:
  media_volume:
  db_volume:
    external:
      name: postgres-data-volume