kind: PersistentVolume
apiVersion: v1
metadata:
  name: nginx-pv-volume
  labels:
    type: local
    app: nginx
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Users/anippard/Programming/jabberwocky/frontend/dist/frontend"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-pv-claim
  labels:
    app: nginx
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi